name: 'Run markdownlint with reviewdog in nofilter mode'
description: '🐶 Run markdownlint with reviewdog on pull requests to improve code review experience.'
author: 'prologic'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-check'
  markdownlint_flags:
    description: "Options of markdownlint command. Default: '.'"
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'zoom-in'
  color: 'purple'
